name: Deploy NextChat

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST_DEV }}
          username: ${{ vars.SSH_USER_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            cd /opt/NextChat
            git reset --hard
            git pull
            docker build -t santabrowser/chatgpt-next-web .
            docker compose --profile no-proxy down
            docker compose --profile no-proxy up -d --build
